version: "3.8"
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=dimsum
      - POSTGRES_PASSWORD=dimsum
      - POSTGRES_DB=dimsum
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
      # - ./init.sql:/docker-entrypoint-initdb.d/create_tables.sql

volumes:
  cache:
    driver: local
  db:
    driver: local
